server:
  port: 81
  shutdown: graceful # 优雅关机

spring:
  application:
    name: waynboot-admin-api
  profiles:
    active: dev,express
  thymeleaf:
    cache: false
    suffix: .html
    check-template-location: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5MB
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  boot:
    admin:
      client:
        url: http://monitor:89/boot-admin
        username: admin
        password: admin

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 120

# 日志配置
logging:
  level:
    com.wayn: info
    org.springframework: info
  file:
    name: ${LOG_PATH_PREFIX:E:/home}/${spring.application.name}/info.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    logfile:
      external-file: ${logging.file.name}
    health:
      show-details: always


# mybatis plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 搜索指定包别名
  typeAliasesPackage: com.wayn.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

# wayn配置
wayn:
  name: wayn
  version: 1.3.0
  email: 166738430@qq.com
  uploadDir: ${UPLOAD_DIR:D:/waynshop/webp}
  adminUrl: http://admin:81
  mobileUrl: http://mobile:82
