version: '3'
services:
  # RabbitMQ，启动报错时执行chmod 777 -R rabbitmq/
  rabbitmq:
    image: rabbitmq:3.12.7-management
    expose:
      - "5672"
      - "15672"
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/plugins/rabbitmq_delayed_message_exchange-3.12.0.ez:/plugins/rabbitmq_delayed_message_exchange-3.12.0.ez
      - ./rabbitmq/plugins/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/lib/rabbitmq
    environment:
      # rabbitmq的初始用户名
      RABBITMQ_DEFAULT_USER: guest
      # rabbitmq的初始密码
      RABBITMQ_DEFAULT_PASS: guest
    security_opt:
      - label=disable
    networks:
      - mall-network
    restart: unless-stopped

  # Elasticsearch服务，启动报错时执行, "chgrp docker ./es, chmod 775 -R es/"
  elasticsearch:
    image: elasticsearch:7.14.0
    expose:
      - "9200"
      - "9300"
    container_name: elasticsearch
    volumes:
      - ./es/data:/usr/share/elasticsearch/data:Z
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD="123456"
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - xpack.security.enabled=false
    security_opt:
      - label=disable
    deploy:
      resources:
        limits:
          memory: 4g
    networks:
      - mall-network
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:6.2.7
    expose:
      - "6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /etc/redis/redis.conf
    networks:
      - mall-network
    restart: unless-stopped

  # MySQL服务
  mysql:
    container_name: mysql
    image: mysql:8.0.33
    # expose:
    #   - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'wayn_shop'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./db-init:/docker-entrypoint-initdb.d
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    command: mysqld --lower_case_table_names=1 --slow_query_log=1 --max_connections=1000 --default-authentication-plugin=mysql_native_password
    networks:
      - mall-network
    restart: unless-stopped

networks:
  mall-network:
    driver: bridge
