version: '3'
services:
  mobile:
    image: ibm-semeru-runtimes:open-17-jdk
    container_name: mobile
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/logs:/home/logs
      - /opt/waynboot-mall/upload:/opt/waynboot-mall/upload
      - ./jars/waynboot-mobile-api.jar:/home/app/waynboot-mobile-api.jar
    restart: unless-stopped
    command: java -Xms512m -Xmx512m -Duser.timezone=GMT+8 -Dfile.encoding=utf-8 -jar /home/app/waynboot-mobile-api.jar
    ports:
      - "82:82"
    environment:
      - TZ=Asia/Shanghai
      - LOG_PATH_PREFIX=/home/logs
      - UPLOAD_DIR=/opt/waynboot-mall/upload
    networks:
      - waynboot-mall_mall-network

  admin:
    image: ibm-semeru-runtimes:open-17-jdk
    container_name: admin
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/logs:/home/logs
      - /opt/waynboot-mall/upload:/opt/waynboot-mall/upload
      - ./jars/waynboot-admin-api.jar:/home/app/waynboot-admin-api.jar
    restart: unless-stopped  
    command: java -Xms512m -Xmx512m -Duser.timezone=GMT+8 -Dfile.encoding=utf-8 -jar /home/app/waynboot-admin-api.jar
    ports:
      - "81:81"
    environment:
      - TZ=Asia/Shanghai
      - LOG_PATH_PREFIX=/home/logs
      - UPLOAD_DIR=/opt/waynboot-mall/upload
    networks:
      - waynboot-mall_mall-network

  message:
    image: ibm-semeru-runtimes:open-17-jdk
    container_name: message
    volumes:
      - /etc/localtime:/etc/localtime
      - /home/logs:/home/logs
      - /opt/waynboot-mall/upload:/opt/waynboot-mall/upload
      - ./jars/waynboot-message-consumer.jar:/home/app/waynboot-message-consumer.jar
    restart: unless-stopped
    command: java -Xms512m -Xmx512m -Duser.timezone=GMT+8 -Dfile.encoding=utf-8 -jar /home/app/waynboot-message-consumer.jar
    expose:
      - "85"
    environment:
      - TZ=Asia/Shanghai
      - LOG_PATH_PREFIX=/home/logs
      - UPLOAD_DIR=/opt/waynboot-mall/upload
    networks:
      - waynboot-mall_mall-network

  monitor:
    image: ibm-semeru-runtimes:open-17-jdk
    container_name: monitor
    volumes:
      - /etc/localtime:/etc/localtime
      - ./jars/waynboot-monitor.jar:/home/app/waynboot-monitor.jar
    restart: unless-stopped
    command: java -Xms512m -Xmx512m -Duser.timezone=GMT+8 -Dfile.encoding=utf-8 -jar /home/app/waynboot-monitor.jar
    expose:
      - "89"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - waynboot-mall_mall-network

  nginx:
    container_name: "nginx"
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /opt/waynboot-mall/upload:/opt/waynboot-mall/upload
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx/
      - ./front/mall:/usr/share/nginx/html/mall/
      - ./front/admin:/usr/share/nginx/html/admin/
    networks:
      - waynboot-mall_mall-network

networks:
  waynboot-mall_mall-network:
    external: true
