server:
  port: 85
  shutdown: graceful # 优雅关机
spring:
  application:
    name: waynboot-message-consumer
  data:
    redis:
      host: redis
      port: 6379
      password:
      database: 0
      timeout: 5000
      expire: 400
      lettuce:
        shutdown-timeout: 100ms
  # 配置rabbitMq 服务器
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    # 消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
    # 虚拟主机名称
    virtual-host: /
    listener:
      simple:
        # 一个消费者最多可处理的nack（未确认）消息数量，默认是250
        prefetch: 250
        # 消息确认方式，其有三种配置方式，分别是none、manual(手动ack) 和auto(自动ack) 默认auto
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1


  boot:
    admin:
      client:
        url: http://monitor:89/boot-admin
        username: admin
        password: admin
        
# 日志配置
logging:
  level:
    com.wayn: info
    org.springframework: info
  file:
    name: ${LOG_PATH_PREFIX:E:/home}/${spring.application.name}/info.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    logfile:
      external-file: ${logging.file.name}
    health:
      show-details: always
